name: Delete Old Docker images

on:
    workflow_call:
        inputs:
            image_name:
                description: 'image name to delete old images'
                default: ''
                required: false
                type: string
            image_tag:
                description: 'specific image tag to delete'
                default: ''
                required: false
                type: string
  

jobs:
    DeleteOldDockerImages:
        runs-on: ubuntu-latest
        steps:
            -   name: Delete dangling images
                run: |
                    docker images
                    docker images -f “dangling=true” -q
                    docker rmi $(docker images -f “dangling=true” -q)